apiVersion: v1
kind: Namespace
metadata:
  name: gilead-hepatitis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: gilead-hepatitis
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: build.way2ai.ru/gilead-hepatitis/frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: gilead-hepatitis
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gilead-hepatitis
  namespace: ingress
spec:
  type: ExternalName
  externalName: frontend.gilead-hepatitis.svc.cluster.local
